language: node_js
node_js:
- '0.10'
install:
- gem install sass -v 3.3.14
- gem install bourbon
- gem install neat
- bundle install --path ./vendor/bundle
- bundle exec bitters install --path ./vendor/sass/bitters
- npm install bower -g
- npm install grunt-cli -g
- bower install
- npm install
script:
- echo "building $TRAVIS_COMMIT"
- echo "BUILD_COMMIT=$TRAVIS_COMMIT" > .env
- grunt release
after_success:
- tar -cvzf "loftili-$TRAVIS_COMMIT.tar.gz" ./public/
- curl --ftp-create-dirs -T "loftili-$TRAVIS_COMMIT.tar.gz" -u $FTP_USER:$FTP_PASS
  "ftp://ftp.sizethreestudios.com/artifacts/loftili/ui/$TRAVIS_COMMIT.tar.gz"
- curl --ftp-create-dirs -T "loftili-$TRAVIS_COMMIT.tar.gz" -u $FTP_USER:$FTP_PASS
  "ftp://ftp.sizethreestudios.com/artifacts/loftili/ui/latest.tar.gz"
- |
  if [ -n "$TRAVIS_TAG" ]
  then
  curl --ftp-create-dirs -T "loftili-$TRAVIS_COMMIT.tar.gz" -u $FTP_USER:$FTP_PASS "ftp://ftp.sizethreestudios.com/artifacts/loftili/ui/$TRAVIS_TAG.tar.gz"
  else
  echo "not pushing as a tagged build a travis tagged build"
  fi
env:
  global:
  - secure: LLd3R8C2+ihQnJSnn+bhVp7hRq3kErAdTGkEzbbZ0hAM8kWxm7H4ejJctcNpg8ngCIIRYVZ8uOoLhat81aUSwBuo7+XeihGoqXoTndXhJSat32FH4LWkp846iRthnTogvnkoHdc7oVWvQoMsUikM83GH6WWvUo4/DERC+NdNgJc=
  - secure: yMmXr0jZpeSSVHjUm0/fdNJthvkiw5OKP8oFn1ynzNsa2Q0s37bEPxPlm7WUWbO2NzqnBrDzUyA3GH2xDDNZMi7IgvwAaZjTR8rr7d+1AWSkDQNAzqYEhvM6+PoaEnO+2SpMgCPKP3z9TwYiDdK9s5KOLfn9Z46y+4rextcViI4=
