language: node_js
node_js:
- '0.10'
install:
- gem install sass
- gem install bourbon
- gem install neat
- bundle install --path ./vendor/bundle
- bundle exec bitters install --path ./vendor/sass/bitters
- npm install bower -g
- npm install grunt-cli -g
- bower install
- npm install
script:
- echo "building $TRAVIS_COMMIT"
- echo "BUILD_COMMIT=$TRAVIS_COMMIT" > .env
- grunt release
after_success:
- tar -cvzf "loftili-$TRAVIS_COMMIT.tar.gz" ./public/
- curl --ftp-create-dirs -T "loftili-$TRAVIS_COMMIT.tar.gz" -u $FTP_USER:$FTP_PASS
  "ftp://ftp.sizethreestudios.com/lofti.li/ui/$TRAVIS_COMMIT.tar.gz"
- curl --ftp-create-dirs -T "loftili-$TRAVIS_COMMIT.tar.gz" -u $FTP_USER:$FTP_PASS
  "ftp://ftp.sizethreestudios.com/lofti.li/io/latest.tar.gz"
env:
  global:
  - secure: OGFA7CXA8nK1hrIFVWlstYe5QK/idUDF+DDXhgdCWQuuFnkzgd6Tt6F1lxC94F7gpvFd07cqQ9ozqjacik3qsGKjjzmwynIrtAxXye0coUyEXHd2rgfrcp5qqfDcv20XHOjdLe8Q7wA8A0PF1PwxdkikvN4OWi+JlKEgabx7Y3o=
  - secure: gJzUbu7hsrd5Z5xsXkgdeAaxfEj1sjpdpRdguJyvVq/47s9d6UbJMgZPshU+vNAHRyOtRAP52M4BHbEJEJ6dUP4SPeEuwj6VFifVP9PcJVEp7LrANkKcylPWTKVKLBQOgMzTIaAiOetPd7Bt75k8U3W2sBXMKSpesOtnXnhnHXI=
