language: node_js
node_js:
- '0.10'
install:
- gem install sass
- gem install bourbon
- gem install neat
- bundle install --path ./vendor/bundle
- bundle exec bitters install --path ./vendor/sass
- npm install bower -g
- npm install grunt-cli -g
- bower install
- npm install
script:
- echo "building $TRAVIS_COMMIT"
- grunt release
after_success:
- tar -cvzf "loftili-$TRAVIS_COMMIT.tar.gz" ./public/
- curl --ftp-create-dirs -T "loftili-$TRAVIS_COMMIT.tar.gz" -u $FTP_USER:$FTP_PASS "ftp://ftp.sizethreestudios.com/loftili/$TRAVIS_COMMIT.tar.gz"
- curl --ftp-create-dirs -T "loftili-$TRAVIS_COMMIT.tar.gz" -u $FTP_USER:$FTP_PASS "ftp://ftp.sizethreestudios.com/loftili/latest.tar.gz"

